// Code generated by cborgen DO NOT EDIT.

package {{.Package}}

{{range .Structs}}
{{if .MsgSizeExpr}}
func (x {{.Name}}) Msgsize() (s int) {
	s = {{.MsgSizeExpr}}
	return
}
{{end}}

func (x *{{.Name}}) MarshalCBOR(b []byte) ([]byte, error) {
	if x == nil {
		return {{rt "AppendNil"}}(b), nil
	}
{{if .MsgSizeExpr}}
	b = {{rt "Require"}}(b, x.Msgsize())
{{end}}
{{if $.UseOmit}}
	{{- if .HasOmit }}
	count := uint32(0)
{{- range .Fields -}}
{{- if .OmitEmpty }}
	if !({{.ZeroCheck}}) { count++ }
{{- else }}
	count++
{{- end }}
{{- end }}
	b = {{rt "AppendMapHeader"}}(b, count)
	{{- else }}
	b = {{rt "AppendMapHeader"}}(b, uint32({{len .Fields}}))
	{{- end }}
	var err error
{{- range .Fields }}
{{- if .OmitEmpty }}
	if !({{.ZeroCheck}}) {
		{{- if .EncodeBlock }}
		{{.EncodeBlock}}
		{{- else }}
		b = {{rt "AppendString"}}(b, "{{.CBORName}}")
			{{- if .EncodeExpr }}
		b, err = {{.EncodeExpr}}
			{{- else }}
		b, err = {{rt "AppendInterface"}}(b, x.{{.GoName}})
			{{- end }}
		if err != nil { return b, err }
		{{- end }}
	}
{{- else }}
	{{- if .EncodeBlock }}
	{{.EncodeBlock}}
	{{- else }}
	b = {{rt "AppendString"}}(b, "{{.CBORName}}")
		{{- if .EncodeExpr }}
	b, err = {{.EncodeExpr}}
		{{- else }}
	b, err = {{rt "AppendInterface"}}(b, x.{{.GoName}})
		{{- end }}
	if err != nil { return b, err }
	{{- end }}
{{- end }}
{{- end }}
{{else}}
	b = {{rt "AppendMapHeader"}}(b, {{len .Fields}})
	var err error
{{- range .Fields }}
	{{- if .EncodeBlock }}
	{{.EncodeBlock}}
	{{- else }}
	b = {{rt "AppendString"}}(b, "{{.CBORName}}")
		{{- if .EncodeExpr }}
	b, err = {{.EncodeExpr}}
		{{- else }}
	b, err = {{rt "AppendInterface"}}(b, x.{{.GoName}})
		{{- end }}
	if err != nil { return b, err }
	{{- end }}
{{- end }}
{{end}}
	return b, nil
}

// DecodeSafe decodes using validated, allocating string handling.
func (x *{{.Name}}) DecodeSafe(b []byte) ([]byte, error) {
	if x == nil {
		return b, {{rt "ErrNotNil"}}
	}
	sz, rest, err := {{rt "ReadMapHeaderBytes"}}(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		key, v, err := {{rt "ReadStringBytes"}}(rest)
		if err != nil {
			return b, err
		}
		switch key {
{{- range .Fields }}
		case "{{.CBORName}}":
			{{.DecodeCaseSafe}}
{{- end }}
		default:
			v, err = {{rt "Skip"}}(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// DecodeTrusted decodes using zero-copy strings and no per-string UTF-8 validation.
func (x *{{.Name}}) DecodeTrusted(b []byte) ([]byte, error) {
	if x == nil {
		return b, {{rt "ErrNotNil"}}
	}
	sz, rest, err := {{rt "ReadMapHeaderBytes"}}(b)
	if err != nil {
		return b, err
	}
	for i := uint32(0); i < sz; i++ {
		keyBytes, v, err := {{rt "ReadStringZC"}}(rest)
		if err != nil {
			return b, err
		}
		key := {{rt "UnsafeString"}}(keyBytes)
		switch key {
{{- range .Fields }}
		case "{{.CBORName}}":
			{{.DecodeCaseTrust}}
{{- end }}
		default:
			v, err = {{rt "Skip"}}(v)
			if err != nil {
				return b, err
			}
		}
		rest = v
	}
	return rest, nil
}

// UnmarshalCBOR implements cbor.Unmarshaler using the Safe path.
func (x *{{.Name}}) UnmarshalCBOR(b []byte) ([]byte, error) {
	return x.DecodeSafe(b)
}
{{end}}
